services:
  school.api:
    image: ${DOCKER_REGISTRY-}schoolapi
    build:
      context: .
      dockerfile: src/School.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080